### ISSUE TITLE
STG: Implementació de la lògica de les pantalles

### ISSUE THREAD

**Issue by sgelabert-dgtic** [GovernIB/sistra2#16]
Implementació de la lògica de les pantalles:
- Mòdul de SuperAdministrador:
  - Gestió d'Entitats
  - Propietats de Configuració
  - Plugins Globals
  - Dominis Globals
- Mòdul d'Administrador d'Entitat / Desenvolupador:
  - Configuració d'entitat
  - Plugins Entitat
  - Gestor de formularis externs
   - Dominis d'Entitat
   - Fonts de dades d'entitat
   - Missatges d'avís d'entitat
   - Rols i permisos
   - Àrees/Tràmits (Àrees, Tràmits, Dominis àrees, Fonts de dades Àrees)

**Comment by rsanz-indra** [comment]
Están implementadas las pantallas indicadas (se ha cambiado la pantalla de Gestor de formularis externs por la de Formateadores). 
Queda pendiente la importación/exportación de Fuente de datos a partir de un CSV.
Subiremos los cambios al Github y mañana subiremos la parte que queda.

**Comment by sgelabert-dgtic** [comment]
Es detecta error de desplegament mòdul sistrages:
```
2018-04-17 08:58:33,230 ERROR [org.springframework.web.context.ContextLoader] (ServerService Thread Pool -- 59) Context initialization failed: org.springframework.beans.factory.parsing.BeanDefinitionParsingException: Configuration problem: Failed to import bean definitions from URL location [classpath:sistrages-ejb-core-api.xml]
Offending resource: ServletContext resource [/WEB-INF/sistrages-ac-frontend-jboss.xml]; nested exception is org.springframework.beans.factory.BeanDefinitionStoreException: IOException parsing XML document from class path resource [sistrages-ejb-core-api.xml]; nested exception is java.io.FileNotFoundException: class path resource [sistrages-ejb-core-api.xml] cannot be opened because it does not exist
	at org.springframework.beans.factory.parsing.FailFastProblemReporter.error(FailFastProblemReporter.java:70)
	at org.springframework.beans.factory.parsing.ReaderContext.error(ReaderContext.java:118)
	at org.springframework.beans.factory.parsing.ReaderContext.error(ReaderContext.java:103)
	at org.springframework.beans.factory.xml.DefaultBeanDefinitionDocumentReader.importBeanDefinitionResource(DefaultBeanDefinitionDocumentReader.java:233)
	at org.springframework.beans.factory.xml.DefaultBeanDefinitionDocumentReader.parseDefaultElement(DefaultBeanDefinitionDocumentReader.java:184)
	at org.springframework.beans.factory.xml.DefaultBeanDefinitionDocumentReader.parseBeanDefinitions(DefaultBeanDefinitionDocumentReader.java:169)
	at org.springframework.beans.factory.xml.DefaultBeanDefinitionDocumentReader.doRegisterBeanDefinitions(DefaultBeanDefinitionDocumentReader.java:142)
	at org.springframework.beans.factory.xml.DefaultBeanDefinitionDocumentReader.registerBeanDefinitions(DefaultBeanDefinitionDocumentReader.java:94)
	at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.registerBeanDefinitions(XmlBeanDefinitionReader.java:508)
	at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.doLoadBeanDefinitions(XmlBeanDefinitionReader.java:392)
	at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.loadBeanDefinitions(XmlBeanDefinitionReader.java:336)
	at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.loadBeanDefinitions(XmlBeanDefinitionReader.java:304)
	at org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanDefinitions(AbstractBeanDefinitionReader.java:181)
	at org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanDefinitions(AbstractBeanDefinitionReader.java:217)
	at org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanDefinitions(AbstractBeanDefinitionReader.java:188)
	at org.springframework.web.context.support.XmlWebApplicationContext.loadBeanDefinitions(XmlWebApplicationContext.java:125)
	at org.springframework.web.context.support.XmlWebApplicationContext.loadBeanDefinitions(XmlWebApplicationContext.java:94)
	at org.springframework.context.support.AbstractRefreshableApplicationContext.refreshBeanFactory(AbstractRefreshableApplicationContext.java:129)
	at org.springframework.context.support.AbstractApplicationContext.obtainFreshBeanFactory(AbstractApplicationContext.java:614)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:515)
	at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:443)
	at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:325)
	at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:107)
	at io.undertow.servlet.core.ApplicationListeners.contextInitialized(ApplicationListeners.java:187)
	at io.undertow.servlet.core.DeploymentManagerImpl.deploy(DeploymentManagerImpl.java:198)
	at org.wildfly.extension.undertow.deployment.UndertowDeploymentService.startContext(UndertowDeploymentService.java:100)
	at org.wildfly.extension.undertow.deployment.UndertowDeploymentService$1.run(UndertowDeploymentService.java:82)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
	at org.jboss.threads.JBossThread.run(JBossThread.java:320)
Caused by: org.springframework.beans.factory.BeanDefinitionStoreException: IOException parsing XML document from class path resource [sistrages-ejb-core-api.xml]; nested exception is java.io.FileNotFoundException: class path resource [sistrages-ejb-core-api.xml] cannot be opened because it does not exist
	at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.loadBeanDefinitions(XmlBeanDefinitionReader.java:344)
	at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.loadBeanDefinitions(XmlBeanDefinitionReader.java:304)
	at org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanDefinitions(AbstractBeanDefinitionReader.java:181)
	at org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanDefinitions(AbstractBeanDefinitionReader.java:217)
	at org.springframework.beans.factory.xml.DefaultBeanDefinitionDocumentReader.importBeanDefinitionResource(DefaultBeanDefinitionDocumentReader.java:227)
	... 29 more
Caused by: java.io.FileNotFoundException: class path resource [sistrages-ejb-core-api.xml] cannot be opened because it does not exist
	at org.springframework.core.io.ClassPathResource.getInputStream(ClassPathResource.java:172)
	at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.loadBeanDefinitions(XmlBeanDefinitionReader.java:330)
	... 33 more
```

**Comment by rsanz-indra** [comment]
Faltaba incluir un fichero de configuración en la compilación de maven. En nuestros entornos locales no fallaba porque se ve que el plugin de JBoss de Eclipse lo incluía.
Como método de comprobación siempre estábamos deployando antes de cada entrega en caibter, pero desde que empezamos a implementar la lógica en las pantallas no lo habíamos actualizado porque nos venía bien tener el prototipo inicial en JSF.
Para evitar que se produzca de nuevo hemos instalado la última versión en caibter e instalaremos otra versión aparte con el prototipo.

**Comment by sgelabert-dgtic** [comment]
Es detecta error no controlat en la gestió de "plugins d'entitat", perfil "Administrador Entitat" [log_error_cercador_plugins.txt](https://github.com/GovernIB/sistra2/files/1919558/log_error_cercador_plugins.txt):
```
Excepció: javax.ejb.EJBException
Missatge: es.caib.sistrages.core.api.exception.ErrorNoControladoException: Error no controlado en la capa de servicio: org.hibernate.QueryException: could not resolve property: instancia of: es.caib.sistrages.core.service.repository.model.JPlugin [select t from es.caib.sistrages.core.service.repository.model.JPlugin as t where t.ambito = :ambito AND t.entidad.codigo = :idEntidad AND ( lower(t.claseImplementadora) like :pFiltro or lower(t.descripcion) like :pFiltro or lower(t.instancia) like :pFiltro) order by t.tipo]
```

**Comment by rsanz-indra** [comment]
Sí, ya lo habíamos detectado y corregido esta mañana junto con alguna otra cosilla.
Si detectáis algo más nos lo comentáis y se arregla para la próxima entrega.

**Comment by sgelabert-dgtic** [comment]
- Configuració Entitat
  - Canviar "Email" per "Email responsable inventari"
  - Controlar al desar si has marcat alguns dels checks de la secció ajuda que estigui informat l'input o la configuració associada.
- Dominis d'Entitat
  - Canviar document d'anàlisi per indicar que es permeter definir "font de dades" a nivell d'entitat o àrea, ara índica únicament a nivell d'àrea.
- Font de dades
  - Error: l'edició no modifica el valor de "Descripció"
- Missatges d'Entitat
  - No apareix el filtre "Tràmits per organisme", l'equivalència seria "àrea" o "entitat" ?
  - Entenc que l'opció "Llista de tràmits" permetria especificar els tràmits. Com es defineixen ?
  - Analitzar si la "data fi" ha de ser un camp obligatori o bé es pot deixar desinformat entenent que així el missatge està actiu des de la data d'inici. En funció d'això valorar també si en els camps data a banda del pick-up de calendari haurien de deixar escriure la data per evitar haver de navegar amb clics amb l'anys.
- Dominis d'àrea / Fonts de dades
  - Afegir molla per poder identificar a quina àrea pertany el domini i endemés retornar a l'area de navegació
- Formatador de formulari
  - Aquesta funcionalitat no apareix reflectida a nivell doc. d'anàlisi ni doc. mockup de pantalles. Ho podeu incloure juntament amb una descripció de la funcionalitat #3?
- Tramits
  - Contemplem el cas en que un tràmit pugui pertànyer a més d'una àrea ? Seria possible moure un tràmit entre àrees ?
  - Error no controlat quan s'esborra una àrea amb tràmits [log_eliminar_area.txt](https://github.com/GovernIB/sistra2/files/1923362/log_eliminar_area.txt)

```
Excepció: javax.ejb.EJBException
Missatge: es.caib.sistrages.core.api.exception.DatabaseException: Error en la capa de base de datos: could not execute statement; SQL [n/a]; constraint [SISTRAGES.STG_FUEDAT_AREA_FK]; nested exception is org.hibernate.exception.ConstraintViolationException: could not execute statement
```

Finalment, mirant el model de dades es veu que els camps "identificadors" (encertadament) no formen part de la clau primària, però a nivell de pantalla no es permet la seva edició.  Endemés aquest identificador és el que s'empra per fer referència a l'element des d'altres pantalles. Podríem permetre l'edició per canviar-li el nom?

**Comment by rsanz-indra** [comment]
Buenas, respondo entre líneas. Existen una serie de mejoras que entiendo que no son críticas y que podríamos apuntarlas para irlas haciendo conforme haya hueco para no ir parando el avance del desarrollo y cumplir hitos (a algunas que has comentado añadiría la gestión de roles, una vez usada veo más práctico tener una lista de roles y al editar mantener todos los permisos de ese roles, es decir, todos los permisos sobre las áreas que se tenga). Si os parece bien apuntamos estas mejoras no críticas en un txt a nivel del proyecto y se acometerán cuando se puedan.

- Configuració Entitat
  - Canviar "Email" per "Email responsable inventari"
    OK
  - Controlar al desar si has marcat alguns dels checks de la secció ajuda que estigui informat l'input o la configuració associada.
  OK
- Dominis d'Entitat
  - Canviar document d'anàlisi per indicar que es permeter definir "font de dades" a nivell d'entitat o àrea, ara índica únicament a nivell d'àrea.
   OK
- Font de dades
  - Error: l'edició no modifica el valor de "Descripció"
   OK
- Missatges d'Entitat
  - No apareix el filtre "Tràmits per organisme", l'equivalència seria "àrea" o "entitat" ?
   EL EQUIVALENTE SERIA "TODOS LOS TRÁMITES", QUE HARÍA REFERENCIA A LOS TRÁMITES DE UNA ENTIDAD
  - Entenc que l'opció "Llista de tràmits" permetria especificar els tràmits. Com es defineixen ?
  SE HA PASADO DE IMPLEMENTAR. DE MOMENTO AÑADIMOS UN INPUT PARA PODER ESTABLECER UNA LISTA DE CODIGOS. MÁS ADELANTE SE PUEDE COMPLICAR MÁS PARA QUE SE PUEDAN SELECCIONAR, ETC. LO APUNTAREMOS COMO UNA MEJORA PARA CUANDO HAYA HUECO.
  - Analitzar si la "data fi" ha de ser un camp obligatori o bé es pot deixar desinformat entenent que així el missatge està actiu des de la data d'inici. En funció d'això valorar també si en els camps data a banda del pick-up de calendari haurien de deixar escriure la data per evitar haver de navegar amb clics amb l'anys.
EN PRINCIPIO NI LA FECHA DE INICIO Y FIN SON OBLIGATORIAS A NIVEL DE BD. SE PODRÍA INTERPRETAR EL PLAZO CONFORME SE QUIERA (NO FECHA INICIO NI FIN, ES QUE HAY QUE MOSTRARLO SIEMPRE).
- Dominis d'àrea / Fonts de dades
  - Afegir molla per poder identificar a quina àrea pertany el domini i endemés retornar a l'area de navegació
  SI OS PARECE APUNTAMOS ESTA FUNCIONALIDAD A LA LISTA DE MEJORAS NO CRÍTICAS
- Formatador de formulari
  - Aquesta funcionalitat no apareix reflectida a nivell doc. d'anàlisi ni doc. mockup de pantalles. Ho podeu incloure juntament amb una descripció de la funcionalitat #3?
    ACTUALIZAMOS DOCUMENTO ANÁLISIS PARA EXPLICAR LA FUNCIONALIDAD. NO MODIFICAMOS EL DE MOCKUP YA QUE LA PANTALLA YA ESTÁ IMPLEMENTADA (EL DOCUMENTO DE MOCKUP TENÍA LA FINALIDAD DE VALIDAR LA PANTALLA ANTES DE IMPLEMENTARLA).
- Tramits
  - Contemplem el cas en que un tràmit pugui pertànyer a més d'una àrea ? Seria possible moure un tràmit entre àrees ?
   ESTA PREVISTO QUE UN TRÁMITE PERTENEZCA A UNA SOLA ÁREA.
   IMPLEMENTAMOS PARA SIGUIENTE ENTREGA PODER MOVER UN TRÁMITE ENTRE ÁREAS.
  - Error no controlat quan s'esborra una àrea amb tràmits [log_eliminar_area.txt](https://github.com/GovernIB/sistra2/files/1923362/log_eliminar_area.txt)

```
Excepció: javax.ejb.EJBException
Missatge: es.caib.sistrages.core.api.exception.DatabaseException: Error en la capa de base de datos: could not execute statement; SQL [n/a]; constraint [SISTRAGES.STG_FUEDAT_AREA_FK]; nested exception is org.hibernate.exception.ConstraintViolationException: could not execute statement
```
ESTA CLASE DE ERRORES PUEDE QUE HAYA ALGUNO MÁS. EL TEMA DE CONTROL DE DEPENDENCIAS LO ESTAMOS METIENDO CONFORME VAMOS IMPLEMENTANDO LOS DAOS CORRESPONDIENTES. A NIVEL DE IMPLEMENTACIÓN YA LO TENEMOS PREPARADO, SOLO QUEDA REALIZAR LA LLAMADA AL DAO.

Finalment, mirant el model de dades es veu que els camps "identificadors" (encertadament) no formen part de la clau primària, però a nivell de pantalla no es permet la seva edició.  Endemés aquest identificador és el que s'empra per fer referència a l'element des d'altres pantalles. Podríem permetre l'edició per canviar-li el nom?

HABILITAMOS LA EDICIÓN DE IDENTIFICADORES LÓGICOS. TAMBIÉN ESTAMOS RESTRINGIENDO EL FORMATO A QUE SEA ALFANUMÉRICO Y EN MAYÚSCULAS (NO ESTÁ EN LA VERSIÓN ACTUAL DEL GIT). ÚNICAMENTE HABRÁ CASOS EN LOS QUE SE DEBA CONTROLAR SI EL CAMBIO DE UN IDENTIFICADOR LÓGICO PUEDA TENER IMPACTO. POR EJEMPLO SI SE CAMBIA UN IDENTIFICADOR DE DOMINIO Y SE USA EN SCRIPTS, EN ESE CASO SE SACARÍA UN AVISO (POR CIERTO, PARA DOMINIOS FALTARÍA UN BOTÓN QUE INDIQUE EN QUE TRÁMITES SE ESTÁ USANDO).

**Comment by sgelabert-dgtic** [comment]
OK, he afegit tiquet #22 per recopilar totes aquestes funcionalitats no crítiques
La única que trob que cal cercar-hi solució és:
> - Dominis d'àrea / Fonts de dades
>   - Afegir molla per poder identificar a quina àrea pertany el domini i endemés retornar a l'àrea de navegació"

El problema que li veig és que quan entres en el Domini d'àrea / Font de dades perds la referència de l'àrea on estàs associant el domini o la font (no apareix ni a nivell de grid). Per això us proposava incorporar la molla de pa que ja apareix en la utilitat de "Tràmits". Si ho veieu molt costós ho passam al #22

**Comment by rsanz-indra** [comment]
Mejor pasar al #22 esta funcionalidad. Si te parece podéis ordenar por prioridad las tareas del #22 y en huecos que haya en el desarrollo se van implementando (puedes poner esta la 1ª de la lista). Conforme se vayan haciendo se indicarán en la entrada.
Así las mejoras no críticas no nos paran el avance.

**Comment by sgelabert-dgtic** [comment]
Actualitzo el tiquet amb la resposta a les qüestions plantejades i una nova revsió després del commit https://github.com/GovernIB/sistra2/commit/96da93c8185d90d3a44b080ad69dbae43635fb28:
- Configuració Entitat
  - Canviar "Email" per "Email responsable procediment"
  - Marcar automàticament el check quan l'input o la configuració associada estan informades
- Missatge d'avís entitat
  - Eliminar obligatorietat dels camps DataInici, DataFi. Si no estan informats el misstage es mostra sempre. Si està informat algun d'ells o ambdòs es mostra missatge segons dates.
- Dominis d'àrea / Fonts de dades
  - He passat la millora de la  molla al tiquet #22. Tot i això, em pareix important perquè es perd referència a l'àrea i es perd la navegació.
- Formatador de formulari
   - Pendent de reflectir aquesta funcionalitat en el doc. d'anàlisi. 
- Tramits
  - He passat permetre moure un tràmit entre àrees al tiquet #19
  -  Error no controlat quan s'esborra una àrea amb tràmits [log_eliminar_area.txt](https://github.com/GovernIB/sistra2/files/1923362/log_eliminar_area.txt)
- Pendent de permetre l'edició d'identificadors lògics

**Comment by rsanz-indra** [comment]
Implementadas las funcionalidades (excepto algunas pospuestas en tarea #22).
Respecto a "Entidad: Marcar automàticament el check quan l'input o la configuració associada estan informades" se ha implementado sacar un mensaje de aviso si se ha marcado un check y no tiene los datos asociados. Si se marcara automáticamente el check si tiene el dato rellenado podría llevar a confusión ya que si se desmarcara y se diera a guardar, se volvería a activar.

**Comment by sgelabert-dgtic** [comment]
Es reobri per revisar dues incidències detectades:
- [Gestió Entitats]  Sobre el camp "Codi Dir3" no es pot fer un "paste"
- [Propietats de configuració global] Amb el perfil de SuperAdministrador no apareix el botó "Nou" en la secció. No es poden mantenir via aplicació ?

**Comment by rsanz-indra** [comment]
- _[Gestió Entitats]  Sobre el camp "Codi Dir3" no es pot fer un "paste"_
Este campo implementa un filtro que limita los carácteres que se pueden introducir (<p:keyFilter regEx="/[a-z0-9_-]/i" />). Este filtro evita por defecto el paste ya que si se hace paste PF no controla los carácteres, se requeriría de forma adicional una validación en servidor. Se modifica pantalla para permitir paste e implementar validación en servidor.

- _[Propietats de configuració global] Amb el perfil de SuperAdministrador no apareix el botó "Nou" en la secció. No es poden mantenir via aplicació ?_
No. Creo que ya se comentó anteriormente, las propiedades de configuración global son propiedades predefinidas por la versión de Sistra por lo que para un mejor control solo se permite su modificación y su inserción/borrado se controla a nivel de los scripts de creación/actualización.

**Comment by rsanz-indra** [comment]
Se permite hacer "paste" en el campo "Codi Dir3" y se añade una validación del contenido del campo en el servidor.

**Comment by sgelabert-dgtic** [comment]
Ara permet "paste" però falla la validació del codi DIR3
![image](https://user-images.githubusercontent.com/17268396/43141493-4c10fbbe-8f56-11e8-9622-22b1ed012301.png)

**Comment by sgelabert-dgtic** [comment]
Amb els darrers canvis relacionats amb l'arbre, no veim com podem donar d'alta un tràmit nou en una àrea

**Comment by rsanz-indra** [comment]
Hay que tener seleccionada 1 única área y desplegar el menú "Más..."

![image](https://user-images.githubusercontent.com/17456494/43187401-92d16976-8ff1-11e8-8df4-a8a148dd99c0.png)

**Comment by sgelabert-dgtic** [comment]
Ho cercava dins l'altra pestanya "Más.." que per cert s'hauria de canviar per "Més...". 
Pens que si a la dreta tenim "Importat, Moure i Eliminar" per coherència també hi hauria d'haver l'opció de "Nou Tràmit".
És més, si m'apures els dominis i fonts de dades quasi que també els mouria dins el menú "Més..." de la dreta i deixaria l'esquerra pel manteniment exclusiu d'àrees (Nou, Editar i Eliminar Àrea)

**Comment by rsanz-indra** [comment]
Ok, realizamos los cambios.
Entendemos que no es necesario modificar los mockups para reflejar estas modificaciones.

**Comment by sgelabert-dgtic** [comment]
No, no es necessari modificar el document de mockups.
Trasllat comentari al tiquet #34
