### ISSUE TITLE
STT: Visualitzar  l'import calculat d'una taxa simulada

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#301]
Visualitzar  l'import calculat segons el codi d'una taxa al propi missatge que diu que el pagament és simulat o al justificant de pagament que ara mateix sols surt la paraula "SIMULADO"

**Comment by jparedes-indra** [comment]
Se resuelve en la versión 1.2.0(c9b2299) y se despliega en CAIBter, pero no en DEV.

**Comment by jsastre-dgtic** [comment]
He importat la v 2 del test-pagaments de dev caib (a dev funciona) amb pagament simulat i dóna error a caibter (1.2):


http://caibter.indra.es/sistramitfront/asistente/iniciarTramite.html?tramite=TEST-PAG&version=1&idioma=ca&servicioCatalogo=false&idTramiteCatalogo=$--SIMULADO--$
org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:88)
	at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:707)
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:660)
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:620)
	at org.springframework.web.client.RestTemplate.getForObject(RestTemplate.java:294)
	at es.caib.sistra2.commons.plugins.pago.paymentib.ComponentePagoPaymentIBPlugin.consultaTasa(ComponentePagoPaymentIBPlugin.java:156)
	at es.caib.sistramit.core.service.component.integracion.PagoComponentImpl.consultaTasa(PagoComponentImpl.java:61)
	at es.caib.sistramit.core.service.component.script.plugins.flujo.PlgPago.consultarTasa(PlgPago.java:43)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:138)
	... 222 more

**Comment by jparedes-indra** [comment]
Hemos resuelto un problema de comunicación con el Proxy en CAIBter. Ahora debería funcionar correctamente.

**Comment by jsastre-dgtic** [comment]
ok, comprovat bon funcionament. Cal canviar "tasa" per "taxa" i col·locar el títol **PAGAMENT SIMULAT** alineat a l'esquerra i no tan junt de la taula.
![image](https://user-images.githubusercontent.com/18436867/123388499-23aa2d80-d599-11eb-92a2-d93e0b752ce4.png)

**Comment by jparedes-indra** [comment]
Se resuelve en el TAG 1.2.0 (9030c09) y se despliega en CAIBter.
