### ISSUE TITLE
STT: Integració amb el plugin d'autenticació

### ISSUE THREAD

**Issue by sgelabert-dgtic** [GovernIB/sistra2#41]
Integració de SISTRAMIT amb el plugin d'autenticació basat en el component horitzontal LOGINIB

**Comment by jsastre-dgtic** [comment]
Com ho configuram per provar-ho?
![image](https://user-images.githubusercontent.com/18436867/46662117-dc966700-cbba-11e8-996f-d6207b458b58.png)

**Comment by amaciam-indra** [comment]
El plugin d'autenticació de mock ja l'estau provant quan accediu a un tràmit a desenvolupament (Ex.: http://sdevapplin5.caib.es:48080/sistramitfront/asistente/iniciarTramite.html?tramite=SA001&version=1&idioma=ca&idTramiteCatalogo=3270471).
Per provar el de loginIB l'haurieu de crear a nivell de plugins globals i instal·lar el component loginIB. Com que hem de crear un document d'instal·lació i configuració del component, podeu aprofitar quan estigui llest per la instal·lació seguint aquest document, de manera que també es validi el document.
Per provar ara mateix tant el plugin com el component loginIB teniu disponible CAIBTER. Podeu provar per exemple amb el tràmit http://caibter.indra.es/sistramitfront/asistente/iniciarTramite.html?tramite=TRAM_SISTRAMIT&version=1&idioma=ca&idTramiteCatalogo=2725307
Pensau que per ara Cl@ve està simulat, ja que estam a l'espera de les respostes del CAID per acabar la adaptació a Cl@ve 2.0.

**Comment by sgelabert-dgtic** [comment]
OK, esperam el document d'instal·lació i configuració del component, mentrestant pas el tiquet a "Diagnòstic" pendent de resoldre les incidències amb CAID relacionades amb Cl@ve2

Respecte al document, a banda de descriure la instal·lació i configuració del component des del punt de vista de SISTRA2, hauria de servir també de guia per la resta d'aplicacions que vulguin consumir els seus serveis. Concretament, servir de base per integrar els serveis LOGINIB dins el nou projecte de CARPETA, suplint així la funcionalitat que oferim ara amb SISTRA-ZONAPER

**Comment by rsanz-indra** [comment]
Serán documentos distintos, la configuración del plugin de autenticación de Sistra2 para LoginIB irá dentro del documento de instalación del STG y por otro lado estará el documento de instalación de LoginIB donde se podría ampliar para además de la instalación/configuración establecer la interfaz de las APIs. De la misma manera si se quiere se pueden ampliar el alcance del resto de tareas de documentación (STG, STT, PAYMENTIB) para incluir la interfaz de las APIs (habría que determinar si se quiere incluir las internas o solo las externas).

Por otra parte esta tarea podría cerrarse ya, puesto que el plugin de Sistra2 para LoginIB está desarrollado. Las tareas pendientes de adaptación son exclusivamente de la tarea LOGINIB#3.

**Comment by amaciam-indra** [comment]
A continuació indicam la configuració de la implementació del plugin d'autenticació per LoginIB. Aquest plugin ha de ser definit com plugin global.

Tipus plugin => Plugin de login
Classname => es.caib.sistra2.commons.plugins.autenticacion.loginib.ComponenteAutenticacionPluginLoginib
Descripció plugin => Plugin d'autenticació LoginIB
Prefix de propietats => plugins.login
Propietats plugin:
- url => URL de l'API Rest del component LoginIB de l'entorn (Ex: http://host:port/loginib/api/rest/v1)
- idAplicacion => SISTRA2

**Comment by jsastre-dgtic** [comment]
Ens dóna error...

![image](https://user-images.githubusercontent.com/18436867/46792296-578a8980-cd43-11e8-96dd-7022f40077c1.png)

![image](https://user-images.githubusercontent.com/18436867/46792312-61ac8800-cd43-11e8-9726-cca932cc9f69.png)


2018-10-11 10:45:23,303 ERROR [es.caib.loginib.core.service.ClaveServiceImpl] (default task-41) Error no controlado en la capa de servicio: java.io.FileNotFoundException: File "A04003003_SamlEngine.xml" cannot be found from path: "/app/jboss-7.0/bin/A04003003_SamlEngine.xml": java.lang.IllegalArgumentException: java.io.FileNotFoundException: File "A04003003_SamlEngine.xml" cannot be found from path: "/app/jboss-7.0/bin/A04003003_SamlEngine.xml"
	at eu.eidas.auth.commons.io.SingletonAccessors.newFileAccessor(SingletonAccessors.java:221)
	at eu.eidas.auth.engine.configuration.dom.ReloadableProtocolConfigurationMapNoMetadata.<init>(ReloadableProtocolConfigurationMapNoMetadata.java:57)
	at eu.eidas.auth.engine.configuration.dom.ProtocolEngineConfigurationFactoryNoMetadata.<init>(ProtocolEngineConfigurationFactoryNoMetadata.java:72)
	at es.caib.loginib.core.service.ClaveServiceImpl.getEngineSamlFactory(ClaveServiceImpl.java:614)
	at es.caib.loginib.core.service.ClaveServiceImpl.generarPeticionLoginClave(ClaveServiceImpl.java:193)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

**Comment by jsastre-dgtic** [comment]
Ja funciona ok. Tancam
