### ISSUE TITLE
Error a l'adjuntar un fitxer en els annexos

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#413]
A l'adjuntar un fitxer en un annex en STT, en la petició POST que es realitza per adjuntar aquest fitxer, aquest s'està duplicant. Per això, augmenta considerablement la mida de la petició, apareixent l'error en el log:

Caused by: org.springframework.web.multipart.MultipartException: Failed to parse multipart servlet request; nested exception is org.apache.commons.fileupload.FileUploadException: UT000020: Connection terminated as request was larger than 10485760 
       at deployment.sistramit.ear//org.springframework.web.multipart.commons.CommonsMultipartResolver.parseRequest(CommonsMultipartResolver.java:168) 
       at deployment.sistramit.ear//org.springframework.web.multipart.commons.CommonsMultipartResolver.resolveMultipart(CommonsMultipartResolver.java:142) 
       at deployment.sistramit.ear.sistramitfront.war//org.springframework.web.servlet.DispatcherServlet.checkMultipart(DispatcherServlet.java:1104) 
       at deployment.sistramit.ear.sistramitfront.war//org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:936) 
       at deployment.sistramit.ear.sistramitfront.war//org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:901) 
       at deployment.sistramit.ear.sistramitfront.war//org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)

**Comment by jparedes-indra** [comment]
Se resuelve en el TAG 1.2.0 (c15dc39) y se despliega en CAIBter

**Comment by jparedes-indra** [comment]
Se resuelve el error comentado que duplicaba el fichero anexado. 

![image](https://user-images.githubusercontent.com/67064375/135094803-e5293b10-7260-4cc1-adb9-666f0f6e158d.png)

**Comment by jsastre-dgtic** [comment]
funcionament correcte
