### ISSUE TITLE
No permetre desar check si no s'introdueix script avís

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#419]
Si no introduim script avís a la passa registrar, falla en el cas de tenir el check marcat.

![image](https://user-images.githubusercontent.com/18436867/135412578-95026c27-122c-48ba-9942-f994947b4912.png)

Error no controlado en la capa de servicio: null

Traça:
es.caib.sistramit.core.api.exception.ErrorNoControladoException: Error no controlado en la capa de servicio: null
	at deployment.sistramit.ear.sistramit-core.jar//es.caib.sistramit.core.interceptor.NegocioInterceptorAspect.auditaExcepcion(NegocioInterceptorAspect.java:214)
	at deployment.sistramit.ear.sistramit-core.jar//es.caib.sistramit.core.interceptor.NegocioInterceptorAspect.processException(NegocioInterceptorAspect.java:140)
	at jdk.internal.reflect.GeneratedMethodAccessor735.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at deployment.sistramit.ear//org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:629)
	at deployment.sistramit.ear//org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:611)
	at deployment.sistramit.ear//org.springframework.aop.aspectj.AspectJAfterThrowingAdvice.invoke(AspectJAfterThrowingAdvice.java:66)
	at deployment.sistramit.ear//org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:168)
	at deployment.sistramit.ear//org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92)
	at deployment.sistramit.ear//org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at deployment.sistramit.ear//org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:213)
	at deployment.sistramit.ear.sistramit-core.jar//com.sun.proxy.$Proxy194.irAPaso(Unknown Source)

**Comment by jparedes-indra** [comment]
Se resuelve en la versión 1.2.1 (eb89edf)

**Comment by jparedes-indra** [comment]
![image](https://user-images.githubusercontent.com/67064375/140876403-311f4a5e-1ae8-4579-bbae-fc4fe684ce5b.png)

**Comment by avillen-dgtic** [comment]
Corregit.
