### ISSUE TITLE
STT: Integració amb el plugin de firma client (FirmaWebSimple)

### ISSUE THREAD

**Issue by sgelabert-dgtic** [GovernIB/sistra2#44]
Integració amb el plugin/API de firma client FirmaWebSimple desenvolupat dins el projecte PortaFIB

**Comment by jsastre-dgtic** [comment]
Com ho configuram per provar-ho? plugins entitat?

**Comment by jsastre-dgtic** [comment]
Ens interessa que el plugin estigui fora de sistra2 i accessible per altres aplicacions. Ho heu pensat i definit així?

**Comment by amaciam-indra** [comment]
En resposta a https://github.com/GovernIB/sistra2/issues/44#issuecomment-428134527:

S'ha d'afegir un plugin de entitat de tipus "Plugin de firma" amb les caracteristiques següents:

Classname => es.caib.sistra2.commons.plugins.firmacliente.firmaweb.ComponenteFirmaSimpleWebPlugin
Prefix de propietats => plugins.firma
Propietats plugin (el usr i pwd us el facilitam per correu):
   url => http://portafib2.fundaciobit.org/portafib/common/rest/apifirmawebsimple/v1/
   usr => ****
   pwd => ****

Per provar la firma s'ha creat un test, ja que aquest funcionalitat estarà en la passa registrar, que no està desenvolupada encara a nivell de lògica. Us indicarem com emprar aquest test.

**Comment by amaciam-indra** [comment]
Respecte al test de la firma, s'ha trobat un problema derivat de la reorganització dels plugins. Ho revisam.

**Comment by sgelabert-dgtic** [comment]
Ok, com comenta en Josep volem que aquest plugin sigui extern i únic per altres aplicacions que necessitin serveis de firma.

**Comment by rsanz-indra** [comment]
El plugin de firma cliente está definido dentro de Sistra2 ya que está pensado sobre la operativa necesaria que requiere el asistente. 
Firmaweb ofrece un API rest para consumir los servicios por lo que si metemos un plugin por encima estaríamos restringiendo la funcionalidad que ofrece este componente (sería el equivalente al API que proporciona LoginIB, PaymentIB o Rolsac, para los que estamos metiendo el plugin en Sistra2 para independizar Sistra2 del componente pero para otras aplicaciones usarían directamente el API del componente).
Confírmadnos si queréis externalizar el plugin de firma de Sistra2 para usarlo, entendemos que para las aplicaciones CAIB. Esto podría tener sentido si se quiere independizar aplicaciones CAIB de FirmaWeb.
En todo caso, lo comentado anteriormente, el plugin está pensado según las necesidades de Sistra2.

**Comment by rsanz-indra** [comment]
Para probar el plugin de firma se ha implementado un test de firma ya que la firma se realizará en el paso de registro todavía pendiente de implementar. 
En la versión actual hay un problema con la gestión de iframes de PortaFIB (subiremos arreglo en la próxima subida a Github). Este error hace que no retorne bien al asistente tras firmar en Portafib, aparece un error javascript (puede hacerse manualmente invocando a /sistramitfront/asistente/recargarTramite.html).

Los pasos para probar serían:
	- iniciar un trámite llegando hasta el paso de anexar y anexando un documento:
		/sistramitfront/asistente/iniciarTramite.html?tramite=TRAM_SISTRAMIT&version=1&idioma=es&idTramiteCatalogo=2725307
	- una vez anexado el documento, introducir manualmente la url de test de firma (dependerá del anexo, en este ejemplo el id anexo = ANEXAR)	
		/sistramitfront/asistente/ad/testFirma.html?idPaso=ad&idAnexo=ANEXAR&instancia=1		
	- se redirigirá a PortaFIB y una vez finalizada la firma se retornara al asistente
	- si la firma se ha realizado correctamente, se podrá descargar introduciendo esta url
		/sistramitfront/asistente/ad/testDescargarFirma.html?idPaso=ad&idAnexo=ANEXAR&instancia=1

**Comment by jsastre-dgtic** [comment]
Confirmam que volem externalitzar el plugin de firma de Sistra2

**Comment by rsanz-indra** [comment]
Apuntamos tarea de externalización del plugin para planificarla. Hay que ver que repositorio de GitHub se utiliza.

**Comment by jsastre-dgtic** [comment]
No aconseguim veure res:

![image](https://user-images.githubusercontent.com/18436867/47067434-aaec5400-d1e9-11e8-84ae-12c60f9417da.png)

![image](https://user-images.githubusercontent.com/18436867/47067453-b770ac80-d1e9-11e8-9b6d-d4a12501bdd6.png)


2018-10-17 08:48:23,435 INFO  [org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor] (default task-90) JSR-330 'javax.inject.Inject' annotation found and supported for autowiring
2018-10-17 08:48:23,440 INFO  [stdout] (default task-90) Hibernate: select hsesiontra0_.SES_CODIGO as SES_CODIGO1_9_, hsesiontra0_.SES_FECHA as SES_FECHA2_9_, hsesiontra0_.SES_IDESTR as SES_IDESTR3_9_ from STT_SESION hsesiontra0_ where hsesiontra0_.SES_IDESTR=?
2018-10-17 08:48:23,442 INFO  [stdout] (default task-90) Hibernate: select STT_LOGINT_SEQ.nextval from dual
2018-10-17 08:48:23,444 INFO  [stdout] (default task-90) Hibernate: insert into STT_LOGINT (LOG_ERRCOD, LOG_EVEDES, LOG_EVEDET, LOG_EVEFEC, LOG_EVERES, LOG_CODSES, LOG_EVETIP, LOG_CODIGO, LOG_ERRDET) values (?, ?, ?, ?, ?, ?, ?, ?, ?)
2018-10-17 08:48:23,451 ERROR [org.jboss.as.ejb3.invocation] (default task-90) WFLYEJB0034: Invocación EJB falló en el componente FlujoTramitacionServiceBean para el método public abstract es.caib.sistramit.core.api.model.flujo.ResultadoAccionPaso es.caib.sistramit.core.api.service.FlujoTramitacionService.accionPaso(java.lang.String,java.lang.String,es.caib.sistramit.core.api.model.flujo.types.TypeAccionPaso,es.caib.sistramit.core.api.model.flujo.ParametrosAccionPaso): javax.ejb.EJBException: es.caib.sistramit.core.api.exception.FlujoInvalidoException: El flujo no es válido
	at org.jboss.as.ejb3.tx.CMTTxInterceptor.handleExceptionInNoTx(CMTTxInterceptor.java:213)
	at org.jboss.as.ejb3.tx.CMTTxInterceptor.invokeInNoTx(CMTTxInterceptor.java:265)
	at org.jboss.as.ejb3.tx.CMTTxInterceptor.notSupported(CMTTxInterceptor.java:313)
	at org.jboss.as.ejb3.tx.CMTTxInterceptor.processInvocation(CMTTxInterceptor.java:237)
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:340)
	at org.jboss.as.ejb3.component.interceptors.CurrentInvocationContextInterceptor.processInvocation(CurrentInvocationContextInterceptor.java:41)
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:340)
	at org.jboss.as.ejb3.component.invocationmetrics.WaitTimeInterceptor.processInvocation(WaitTimeInterceptor.java:43)
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:340)
	at org.jboss.as.ejb3.security.SecurityContextInterceptor.processInvocation(SecurityContextInterceptor.java:100)
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:340)
	at org.jboss.as.ejb3.deployment.processors.StartupAwaitInterceptor.processInvocation(StartupAwaitInterceptor.java:22)
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:340)
	at org.jboss.as.ejb3.component.interceptors.ShutDownInterceptorFactory$1.processInvocation(ShutDownInterceptorFactory.java:64)
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:340)
	at org.jboss.as.ejb3.component.interceptors.LoggingInterceptor.processInvocation(LoggingInterceptor.java:66)
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:340)
	at org.jboss.as.ee.component.NamespaceContextInterceptor.processInvocation(NamespaceContextInterceptor.java:50)

**Comment by rsanz-indra** [comment]
Vuestro anexo tiene el id "ANEXAR"?
/sistramitfront/asistente/ad/testFirma.html?idPaso=ad&idAnexo=**ANEXAR**&instancia=1
Tal como se comentaba en las instrucciones, tenéis que poner el id de anexo que hayáis definido en STG.

**Comment by jsastre-dgtic** [comment]
JA HEM ACONSEGUIT REPRODUIR LES PASSES. Tancam...

**Comment by rsanz-indra** [comment]
Sí, lo comentábamos también en las instrucciones de prueba:

> En la versión actual hay un problema con la gestión de iframes de PortaFIB (subiremos arreglo en la próxima subida a Github). Este error hace que no retorne bien al asistente tras firmar en Portafib, aparece un error javascript (puede hacerse manualmente invocando a /sistramitfront/asistente/recargarTramite.html).

Haced la vuelta manualmente ya que es una prueba y deberá implementarse bien cuando se integre en el paso registrar.

**Comment by sgelabert-dgtic** [comment]
Deixam el tiquet doncs pendent de revisió fins que es solucioni el problema de la redirecció.

**Comment by rsanz-indra** [comment]
Ya se ha solucionado el tema de la redirección

**Comment by jsastre-dgtic** [comment]
Comprovat. Tancam issue

**Comment by jsastre-dgtic** [comment]
INDRA diu:

_Se ha desarrollado, y probado en entornos Indra, el procesado del formato de la firma. En todo caso, de manera posterior a estas pruebas Toni Nadal ha modificado PORTAFIB 2.0, 
y por extensión el API, de manera que se ha tenido que adaptar el plugin de firma para poder compilar SISTRA2. Esto, unido a que se está pendiente de concretar temas de la
parte servidora de PORTAFIB 2.0, hace que esta incidencia esté viva y no se pueda validar en su totalidad.

Si de todas maneras se quisiera hacer pruebas de firma cliente, los pasos a seguir son los siguientes:

1. Acceder a trámite test (sdevapplin6.caib.es:58080/sistramitfront/asistente/iniciarTramite.html?tramite=TEST-JUNIT&version=1&idioma=ca&idTramiteCatalogo=3270471)

2. Seleccionar autenticación con Cl@ve y adaptar los datos del usuario simulado a los del firmante que hará la prueba.

3. Llevar a cabo los diferentes pasos del trámite y pulsar "Firmar" en el paso 4 "Registrar"._

**Comprovat i funciona OK**

**Comment by rsanz-indra** [comment]
A la espera de que se libere versión de PORTAFIB

**Comment by jsastre-dgtic** [comment]
Esperam alliberació de portafib per tancar.

**Comment by rsanz-indra** [comment]
Según comentado con Salvador, se deja la verificación de firmas exclusivamente en la issue #128

**Comment by sgelabert-dgtic** [comment]
Es detecta un error al iniciar la sessió de signatura client. S'adjunta log del resultat de les proves amb el tràmit de TEST_FIRMA http://tn.caib.es/TQKGTdbpiA3P

**Comment by sgelabert-dgtic** [comment]
Després d'actualitzar el perfil de firma obtenim error amb la recuperació del fitxer firmat recuperarResultadoFirmaExterna()
Adjunt log de l'error http://tn.caib.es/PWoaLyedTS62

**Comment by sgelabert-dgtic** [comment]
Link actualitzat amb el log d'error: http://tn.caib.es/27bXQtUbSAZp

**Comment by rsanz-indra** [comment]
PFIB está devolviendo como firma para PDF el tipo TF05 (cades attached), en lugar de PADES.
Este tipo no está soportado actualmente. Se modifica integración para soportar tipos TF03 y TF05 (firmas attached).
Se queda a la espera de que PFIB revise la configuración de perfiles para verificar la integración.

**Comment by rsanz-indra** [comment]
Tras regenerar EAR borrando dependencias locales de FBit, da este error:

Caused by: org.fundaciobit.apisib.core.exceptions.ApisIBServerException: Error desconegut intentant autenticar petició REST: javax.persistence.PersistenceException: org.hibernate.exception.JDBCConnectionException: could not load an entity: [es.caib.portafib.jpa.UsuariAplicacioJPA#$sistra_portafib]

Quedamos pendiente de que se revise configuración PFIB.

**Comment by rsanz-indra** [comment]
Ya funciona la firma: se ha probado a firmar un pdf (retornando pades) y un docx (retornando cades).
La validación de firma se ha realizado correctamente también.

**Comment by jsastre-dgtic** [comment]
Provant el tràmit TEST-FIRMA (V2)
Caused by: es.caib.sistramit.core.api.exception.SesionFirmaClienteException: Excepción al enviar fichero a firmar

**Comment by rsanz-indra** [comment]
Se han producido cambios en el API de FirmaWeb que requieren adaptaciones en S2
