### ISSUE TITLE
Solucionar el problema apareix en introduir caràcters especials en la validació de l'IBAN.

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/sistra2#485]
Solucionar el problema apareix en introduir caràcters especials en la validació de l'IBAN.

![image](https://user-images.githubusercontent.com/18436867/154481447-17fefc60-7a38-4cfe-aabc-15fcea927135.png)

Caused by: java.lang.NumberFormatException: Illegal embedded sign character 
       at java.base/java.math.BigInteger.<init>(BigInteger.java:492) 
       at java.base/java.math.BigInteger.<init>(BigInteger.java:672) 
       at deployment.sistramit.ear//es.caib.sistra2.commons.utils.ValidacionesTipo.checkIBAN(ValidacionesTipo.java:1047) 
       at deployment.sistramit.ear//es.caib.sistra2.commons.utils.ValidacionesTipo.esNumeroCuentaIbanValido(ValidacionesTipo.java:236) 
       at deployment.sistramit.ear.sistramit-core.jar//es.caib.sistramit.core.service.component.script.plugins.PlgUtils.esNumeroCuentaIbanValido(PlgUtils.java:85)

**Comment by aagudo-indra** [comment]
Se resuelve en el TAG 1.3.0_0 (3f14e22).

Ya no salta excepción al comprobar el IBAN, sino que la función retorna un false y se puede validar correctamente el valor: 

<img width="369" alt="image" src="https://user-images.githubusercontent.com/88820558/161045738-8151a5a9-d72b-434e-9b35-199261ecbc1b.png">

<img width="426" alt="image" src="https://user-images.githubusercontent.com/88820558/161045716-76abdc49-fee5-423b-9bb1-2f111534bbb1.png">

<img width="364" alt="image" src="https://user-images.githubusercontent.com/88820558/161045768-3581243e-43b2-415d-ac58-b64d3e303345.png">

**Comment by jsastre-dgtic** [comment]
Això ho controlau per script o automàticament per la validació del camp? Què passa si no posam script?

**Comment by jsastre-dgtic** [comment]
Validam aquesta issue i en cream una altra per afegir a la tipificació dels camps l'IBAN
